# deploy/k8s/configs/redis-common-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: exchange
data:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"